### ISSUE TITLE
Update documentation to include guidelines on PRs

### ISSUE THREAD

**Issue by elsevers** [Severson-Group/severson_group_git#33]
Add brief guidelines on what makes an effective PR. I have started doing this in a tutorial step:

> Log into GitHub and create a pull request to merge your topic branch into develop. Take this as an opportunity to practice writing an informative description in your pull request using markdown styling (a pull request description should give us the narrative of why you have made changes and any important items that the reviewer should pay attention to; your goal is to make reviewing your PR as easy and efficient for your reviewer as possible). Add an appropriate label to the pull request and a reviewer (@elsevers).

It would be good to also provide a subsection in this document on best practices. Is there a blog post or guideline somewhere that we could be linking to? 

Let's also pick an exemplary PR from one of our public repositories to link to as an example of an effective PR.

**Comment by npetersen2** [comment]
@elsevers these look like pretty nice blog post about PRs:

- https://betterprogramming.pub/how-to-make-a-perfect-pull-request-3578fb4c112
- https://hugooodias.medium.com/the-anatomy-of-a-perfect-pull-request-567382bb6067
- https://github.blog/2015-01-21-how-to-write-the-perfect-pull-request/

**Comment by elsevers** [comment]
Thanks @npetersen2! I like these blog posts -- the second one seems especially useful. Do you mind adding links to them and a brief blurb?
